### ISSUE TITLE
[Infra] 모니터링 서비스 도입

### ISSUE THREAD

**Issue by workdd** [ddps-lab/research-infrastructure#8]
프로메테우스, datadog 등 툴 특정 정리 및 도입

**Comment by workdd** [comment]
Grafana를 통해 bento serve 메트릭 파악 예시
그라파나를 연동해 모니터링 ui 구성을 해보았습니다. 실제로 어떤 메트릭들을 수집할 수 있을지 더 파악해보겠습니다.
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/28581495/230267476-ac35a142-f90d-4802-9124-aa356af0435a.png">

**Comment by kmu-leeky** [comment]
재강아 이왕 한다면 프로메테우스도 함께.. 다른 과제에서 활용할것 같아.

**Comment by workdd** [comment]
네 교수님 프로메테우스 + 그라파나 조합으로 모니터링을 진행할 수 있도록 환경 구성에 있습니다.
그라파나는 구성만 해둔 것으로 현재 메트릭들을 가져오는데, 프로메테우스 쪽에 추가적으로 설정이 필요한 듯 보입니다. 추가적으로 더 진행해보겠습니다.

**Comment by workdd** [comment]
현재 구성에 대해 제가 잘못 이해하고 있던 부분이 있었습니다.
그라파나는 단순 ui 모니터링 툴이며 확인되는 cpu usage, memory usage 등은 모두 프로메테우스가 내부적으로 각 pod에 대해서 지속적으로 추적하고 추적된 정보를 grafana가 가져와 ui로써 보여주기만 하는 구성입니다.

아래 사진과 같이 sum(...) by (pod) 와 같은 쿼리문이 내부적으로 실행되며 이것들은 프로메테우스가 수집하고 있는 메트릭을 가져오는 쿼리 문입니다. 해당 쿼리문을 통해 pod들의 정보를 가져와 그라파나는 graph와 같은 ui로 보여주게 됩니다.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/28581495/230273080-93da4d07-feb4-44e3-b159-66b94b5b1225.png">

아래와 같이 프로메테우스 ui에 접속해서 같은 query들을 요청해 보며 메트릭을 수동으로 직접 가져오거나 쿼리문에 대한 리턴값을 미리 테스트 해볼 수 있으며, 그라파나가 보여줄 데이터에 대해 query문을 수정하여 원하는 메트릭을 가져오도록 설정할 수 있습니다. 
(아래 query문은 정상 동작하지 않는 쿼리문이며 예시로써 단순 표현만 해보았습니다.)
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/28581495/230273263-3a7b6729-eb0c-4dcf-8c34-f7625303e890.png">

따라서 지금 기본으로 프로메테우스가 가져오는 각 pod에 대한 cpu, memory usage에서 추가적으로 bentoml의 inference time이나, 실행 end to end time들을 가져올 수 있도록 프로메테우스의 쿼리문 구성에 대해 조금 더 이해하고 구성하는 작업을 진행할 예정입니다.

**Comment by kmu-leeky** [comment]
아 오케이. 메트릭 수집은 프로메테우스, UI 는 그라파나 구나. good to know.

**Comment by mh3ong** [comment]
#20 을 통해 prometheus, grafana을 도입하는 것을 완료했습니다.

다른 추가적인 metric 수집 관련 내용은 다른 issue에서 관리하겠습니다.
